name: first pipeline

on: 
  workflow_dispatch

jobs:
  Terraforminit:
        runs-on: self-hosted
        steps:
        
        - name: Checkout repo
          uses: actions/checkout@v3
          
        - name: Terraform Init
          id: init
          run: terraform init -input=false
          working-directory: ./Env

  Terraformplan:
      runs-on: self-hosted
      steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        working-directory: ./Env

