name: first pipeline

on: 
  workflow_dispatch

jobs:
  newpipeline:
        runs-on: self-hosted
        steps:
        - name: Terraform Init
          id: init
          run: terraform init -input=false
